### ISSUE TITLE
Change user avatar

### ISSUE THREAD

**Issue by Lampwick** [Litarvan/lightdm-webkit-theme-litarvan#1]
How can I change individual user avatars?

**Comment by Litarvan** [comment]
It uses your account avatar. To change it, for me on KDE it was in my system parameters, but i think you can find it on google.

**Comment by EgZvor** [comment]
@Litarvan Does not seem to work for me on Lightdm, can you elaborate on how it searches the system avatar?

**Comment by Litarvan** [comment]
As i said, i don't really know where it searches. The path is given by the API, and for me i set it using my desktop. Tbh google will help you more than I

**Comment by dartzon** [comment]
The solution to this issue is in the Arch linux's wiki, here is a link:
https://wiki.archlinux.org/index.php/LightDM#Changing_your_avatar

**Comment by Remyks** [comment]
or try : /home/username/.face
