### ISSUE TITLE
[Feature Request] Disable shutdown screen

### ISSUE THREAD

**Issue by DustyTopology** [Litarvan/lightdm-webkit-theme-litarvan#103]
It would be nice if we could disable the screen that shows the "Shutting Down...", "Hibernating...", etc. messages after clicking one of the power buttons in the login screen.

**Comment by Litarvan** [comment]
Implemented on 3.2.0, thanks for your request!

**Comment by momozahara** [comment]
maybe put a warning message on this because stuck on Hibernating... screen after resume

**Comment by preampinbut** [comment]
> Implemented on 3.2.0, thanks for your request!

maybe put a warning message or do something with it because we will stuck on Hibernating... screen after resume
