### ISSUE TITLE
Adding Qtile icon

### ISSUE THREAD

**Issue by stonefeld** [Litarvan/lightdm-webkit-theme-litarvan#107]
I'm a Qtile user and i really like your lightdm-greeter but unfortunately your greeter had no icon for Qtile. So I managed some months ago to make an icon and add the required lines in the SelectItem.vue file to make it work. I was thinking of pushing a commit with this changes because I'm pretty sure many other people had a similar problem, but I wasn't sure if I was allowed to do such thing. In any case I leave here the picture of my icon in case you want to add it by yourself, or just tell me if you want me to push my commit.
![qtile](https://user-images.githubusercontent.com/66036447/95154803-11693480-0769-11eb-9963-3944b42f32c2.png)

**Comment by Gorzen** [comment]
Hey @TheoStanfield,
What a coincidence I also wanted to add Qtile I made a pull request #111 
When it will be accepted, there will be Qtile :)

**Comment by TheoStanfield** [comment]
Great @Gorzen,
So we just need to wait until they accept your pull request. I have it already running in my computer though, but I just wanted that other people using Qtile could have a nice icon on their DM.

**Comment by jorgebodega** [comment]
I came here just to see that this issues could be considered closed, as #111 is merged and currently on master. I think we shall wait until next release (or maybe release a `lightdm-webkit-theme-litarvan-git` or similar that points the last commit on AUR if you are using Arch)

**Comment by Litarvan** [comment]
This was released on the 3.2.0, thanks for your suggestion (and @Gorzen for your pull request)!
