### ISSUE TITLE
Greeter very slow

### ISSUE THREAD

**Issue by CocaineJohnsson** [Litarvan/lightdm-webkit-theme-litarvan#108]
In reference to #73, it was initially slow when running the git build of the greeter theme, but I chalked it up to it being the git build, I'd have reported it earlier but life keeps getting in the way.

It's not slow in the debug run (`termite -e "lightdm-webkit2-greeter"`)

To quantify what I mean by slow, I will type my password and hit enter, it will then take approximately 6 seconds for it to complete the typing sequence and initiate a login event.

Running nvidia proprietary driver version 450.66.

Since it started with the 4K fix being introduced I'd assume that's related, something to do with the blur or scaling maybe? Almost certainly rendering related if I'd have to hazard a guess (though I'm not sure why it doesn't happen in the debug window, even when full-screened... the only thing I can think of is that the actual greeter runs on a triple monitor setup, and the debug window only fullscreens to one screen). Multi-monitor issue maybe?

**Comment by pythys** [comment]
I confirm having the same issue. The typing is very slow.

Based on your input I have 2 things that I suspect in my environment:
- nvidia driver
- 4K display

**Comment by Litarvan** [comment]
lightdm-greeter2-greeter uses an old and buggy webkit version, and it doesn't like having transitions on the blur filters. This is what causes the lags on some setups.

I added a 'Blur settings' view in the 3.2.0 (which can be accessed from the setup view) where you can select the blur method that works the best for you. It should fix your issue or at least provide the best workaround.
