### ISSUE TITLE
option to disable splash screen

### ISSUE THREAD

**Issue by Lahorde** [Litarvan/lightdm-webkit-theme-litarvan#11]
I would like to disable splash screen. I've modified `/components/app/app_component.dart` to set duration to 0.1 or 0 but it did not changed anything.

**Comment by Litarvan** [comment]
Will be added to 3.0 :)

**Comment by AichP** [comment]
@Lahorde Tried the same, looking forward to 3.0 @Litarvan :smiley:

**Comment by Litarvan** [comment]
Hi, i'm currently hard working on it, i wanted to know if by "splash" you meant the "Arch Linux" logo fade, or the "Press "Enter" or "Space"" screen ?

**Comment by hkeward** [comment]
@Litarvan is it possible to alter the logo that shows up from Arch to something else - I am using this on Debian.

**Comment by Litarvan** [comment]
You're welcome ! I'm planning to add all the common distros logos for 3.0, but for now patching the .svg is the simplest way to do it :)

**Comment by Lahorde** [comment]
I just seen 3.0 setup window! It's perfect, I hope it will be integrated in master soon.
