### ISSUE TITLE
Limit image height in background picker

### ISSUE THREAD

**Issue by Mrfiregem** [Litarvan/lightdm-webkit-theme-litarvan#112]
When a background is too tall, you're unable to change the background since it continues off the screen, bringing the buttons with them. I fixed this by temporarily moving the tall wallpapers from `/usr/share/backgrounds` and setting a new wallpaper, but setting a max height for the preview or at least being able to use the arrow keys to cycle through them would be better.

**Comment by nikoksr** [comment]
Currently experiencing the same issue. Thanks for the temporary fix @Mrfiregem.

**Comment by Litarvan** [comment]
Should have been fixed on 3.2.0
