### ISSUE TITLE
Blur transitions look messy

### ISSUE THREAD

**Issue by iwonbigbro** [Litarvan/lightdm-webkit-theme-litarvan#113]
There is some weird stuttering happening in the blur transition.  Pretty sure it's a result of the 1080p lagging fixes that were put in place.  It effectively pauses at the end of the transition, but you get a 2x2 grid on the screen running in 2k resolution.  I attached a video, where you can see this grid forming at the end of the transition, before it ends with a fully blurred screen.

https://user-images.githubusercontent.com/4006083/105407374-8df32680-5c25-11eb-89e7-f26282886163.mp4

**Comment by Litarvan** [comment]
lightdm-greeter2-greeter uses an old webkit version which is pretty buggy, and those kind of behaviors can't be reprocued anywhere else than on the greeter itself, but I did my best trying to do so.

I added a 'Blur settings' view (which can be accessed from the setup view) where you can select the blur method that works the best for you. It should fix your issue or at least provide the best workaround.
