### ISSUE TITLE
Theme not loading properly due to JavaScript error

### ISSUE THREAD

**Issue by rhearmas** [Litarvan/lightdm-webkit-theme-litarvan#114]
Self-explanatory issue. I searched through previous issues on this repo, but nothing helpful came up.

The default theme installed with LightDM-Webkit works fine. However, using this theme (litarvan) results in this snippet being at the top of `/var/log/lightdm/seat0-greeter.log`:

```
file:///usr/share/lightdm-webkit/themes/litarvan/js/app.fc965120.js:1:13054: CONSOLE JS ERROR TypeError: undefined is not an object (evaluating 'r.user.username')

** (lightdm-webkit2-greeter:13292): WARNING **: 12:08:17.321: [ERROR] :: A problem was detected with the current theme. Falling back to default theme...
```

I threw the code through a pretty-printer and tried to use the theme again, and I was able to find the exact part of the code that was causing me issues:

```js
// lines 292 through 294
lightdm.users.forEach((function(e) {
    return r.user.username === e.username && (r.user = e)
}))
```

[Here is a paste of the pretty-printed code](http://ix.io/2NF3) so you are seeing what I am seeing. I'm using Arch Linux with kernel 5.10.11-zen.

**Comment by Litarvan** [comment]
This should have been fixed in 3.2.0, keep me updated if it works for you
