### ISSUE TITLE
login window won't pop up

### ISSUE THREAD

**Issue by StathisKap** [Litarvan/lightdm-webkit-theme-litarvan#117]
I'm using Ubuntu 20.4 and runnig web-greeter as a greeter-session ( so greeter-session = web-greeter on the lightdm.conf)

I downloaded litarvan from source, and put in the themes folder of web-greeter at /usr/share/web-greeter. When I try to log in, i get 2 problems. 1, I've change the Os png to the ubuntu one but it isn't show up, 2, the login popup window won't show up and i'm left with a blurry screen. Help

I ran "web-greeter 2>log.txt" to give you guys more info in case it helps
[log.txt](https://github.com/Litarvan/lightdm-webkit-theme-litarvan/files/6012205/log.txt)

This is how the no pop-up
![greeter](https://user-images.githubusercontent.com/69547998/108546284-d400e000-72e0-11eb-8c6f-c389aa23e62b.png)

This is the no-Logo
![logo](https://user-images.githubusercontent.com/69547998/108546289-d5320d00-72e0-11eb-8f4a-b755acd044f1.png)

**Comment by Litarvan** [comment]
'web-greeter' is actually a rewrite of 'lightdm-webkit2-greeter' with a completely different engine, which was never truly finished iirc.
To make the theme work, you need to use the stable version which you can find here https://github.com/Antergos/web-greeter/tree/stable
