### ISSUE TITLE
Focus password input field by pressing Tab key

### ISSUE THREAD

**Issue by graves501** [Litarvan/lightdm-webkit-theme-litarvan#119]
Hi, thank you so much for providing this great theme!

I was just wondering if it's possible to focus the password input field by pressing the tab key, just like in every other input form on the web. 
It would make more accessible and less tedious when using a multi-monitor setup (sometimes the mouse ends up on a different screen and then you are required to drag the mouse from one end to the other).

Thanks for your consideration!

**Comment by Litarvan** [comment]
Unfortunately, the password field is already being auto focused and can also be focused using tab, but the reason it isn't on multi-monitors setup is that as you said, the mouse is on a different screen.

The thing is, until you dragged your mouse to the right screen, neither your mouse or your keyboard will affect the theme, and that's the way lightdm-webkit2-greeter is made (I can't affect this by editing the theme).

lightdm-webkit2-greeter is discontinued now, I will have to make a fork someday to fix the several issues such as this one, but for now I still can't do anything about it in the theme itself.
