### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by patrick-motard** [Litarvan/lightdm-webkit-theme-litarvan#12]
This was the first custom theme I had  installed for lightdm. I read through the [arch wiki lightdm section](https://wiki.archlinux.org/index.php/LightDM) before reading through the install instructions on this repo. Both were not enough to get this theme up and running. 

I went searching through other lightdm-webkit themes repos to see if i could find more information and found [bryanbecker's GlitchDM](https://github.com/bryanbecker/glitchdm). His readme provided more insight. 

Because I was new to all this, there were some questions I didn't know the answers to. Below I've documented the exact steps i followed to get this project working "from scratch".  Would you approve a pull request adding these steps to the README for others to see?

I think it would also be appropriate to point future users to the Arch Wiki arcticle on LightDM so that they can get a broad overview. The wiki helped me understand what a greeter was, for example. 

Otherwise, the theme worked perfectly!

Here is a full list of instructions I had to follow:

**Install Package and Dependencies:**

```
sudo pacman -S lightdm lightdm-webkit2-greeter
yaourt -S lightdm-webkit2-theme-litarvan
```

**Configure lightdm to use `lightdm-webkit2-greeter` as it's greeter**

Edit `/etc/lightdm/lightdm.conf` to include:

```
[Seat:*]
greeter-session=lightdm-webkit2-greeter
session-wrapper=/etc/lightdm/Xsession
```

**Configure `lightdm-webkit2-greeter` to use `litarvan` theme:**

Edit `/etc/lightdm/lightdm-webkit2-greeter.conf` to include:

```
[greeter]
webkit_theme = litarvan
```

(In your readme you say `/etc/lightdm/lightdm-webkit.conf` which i'm not sure is correct. Please correct me if I'm wrong.)

**Ensure `lightdm.service` is enabled on startup**

```
sudo systemctl enable lightdm.service
```

**Try it out**

```
sudo systemctl start lightdm.service
```

or 

```
shutdown -r now
```

**Comment by Litarvan** [comment]
You are right that if you are new to lightdm it isn't probably simple, i would accept a such pull request ! Oh and, for the conf file, it changes depending on the versions
