### ISSUE TITLE
💡: How to hide username when Full Name is present?

### ISSUE THREAD

**Issue by joe733** [Litarvan/lightdm-webkit-theme-litarvan#123]
Hi thank you for this theme. I guess the question is obvious... Hide **jovial** when `Jovial Joe Jayarson` is present.
![photo_2021-04-26_15-54-47](https://user-images.githubusercontent.com/38415384/116068323-bf0d4800-a6a7-11eb-888a-b37541ddd242.jpg)

**Comment by Litarvan** [comment]
Pull request implementing this was merged!
