### ISSUE TITLE
Portuguese (Brazilian) Language Support

### ISSUE THREAD

**Issue by andreluizs** [Litarvan/lightdm-webkit-theme-litarvan#14]
Hi,
Can you add support for the Portuguese (Brazilian) language?
Thank you.

**Comment by andreluizs** [comment]
I found the file: lib/translations.dart

**Comment by Litarvan** [comment]
I don't speak any word of portuguese, but if you want to make translations yourself, you are welcome !  Anyway i can let this issue opened until someone decide to make it ! Still, if you want to do it, the file where the translations are is there : https://github.com/Litarvan/lightdm-webkit-theme-litarvan/blob/master/lib/translations.dart

If you don't know how to code in dart, put the translations here and i'll manage to update it myself

**Comment by prodigyofcodeginn** [comment]
I'll do it.
I'm gonna start tomorrow.

**Comment by prodigyofcodeginn** [comment]
@Litarvan , added Portuguese translation! :)
Please, change this

+        case 'deutsch':
+            return PORTUGUESE[key];
+            break;

to this:

+        case 'portuguese':
+            return PORTUGUESE[key];
+            break;

I think it should be right this way ;)

**Comment by Litarvan** [comment]
Great! Can you commit and create a pull request ?

**Comment by prodigyofcodeginn** [comment]
@Litarvan , I think I've made it. I don't know how to use those options, but please check if I created a pull request.
