### ISSUE TITLE
this code just like an art

### ISSUE THREAD

**Issue by ArchKubi** [Litarvan/lightdm-webkit-theme-litarvan#157]
who codes like this BRUH
![2022-02-15-154705_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/154065052-31addc37-59c6-42fb-9dff-20badf765a6d.png)

**Comment by Litarvan** [comment]
Absolutely no one, this is generated code 🤣! As you can see on this GitHub repository the source code doesn't like like this at all.

**Comment by DaemonOnUnix** [comment]
> who codes like this BRUH ![2022-02-15-154705_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/154065052-31addc37-59c6-42fb-9dff-20badf765a6d.png)

Who put underage japanese girls on his desktop ? That's cringe 👀

**Comment by ArchKubi** [comment]
![2022-02-15-214209_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/154127891-dca2cd99-da84-4c14-8ddd-9bc8735cb1ed.png)
why code open like this ????

**Comment by DaemonOnUnix** [comment]
Ram or Rem ? Who is Rem ?

**Comment by SDAChess** [comment]
This has got the be one of the funniest exchanges I've seen on Github.

**Comment by ArchKubi** [comment]
someone help me god pleaseee

**Comment by d4ilyrun** [comment]
> ![2022-02-15-214209_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/154127891-dca2cd99-da84-4c14-8ddd-9bc8735cb1ed.png) why code open like this ????

You seem to have opened the `dist` folder. You are not supposed to edit what's in it, its content is automatically generated at build time and isn't supposed to be edited or read.
You should open the `src` folder instead, it's where the original source files are located.

**Comment by Vinetos** [comment]
Is this code golfing ?

**Comment by ArchKubi** [comment]
what ? ı don't understand what you mean code golfing?
