### ISSUE TITLE
HiDPI Support

### ISSUE THREAD

**Issue by CBCOOPER** [Litarvan/lightdm-webkit-theme-litarvan#18]
Is it possible to adjust settings to scale for HiDPI monitors?

**Comment by Litarvan** [comment]
Can you try to launch the greeter in debug mode using, in an already existing desktop session, the command `lightdm-webkit2-greeter` in a shell ? And send me a screenshot ? So i can look what it looks like

**Comment by CBCOOPER** [comment]
![2018-05-29-161923_3200x1800_scrot](https://user-images.githubusercontent.com/30965751/40683328-49ad9f4c-635c-11e8-874d-ac3be335f44a.png)

Here you are. It looks normal when launched this way, however, the scale is skewed when launched by the display manager

**Comment by Litarvan** [comment]
I understand, i'll try to x2 them on hdpi, never did this but i'll try with media queries ! (Also, your polybar theme is pretty nice)

**Comment by Litarvan** [comment]
Fixed in 3.0
