### ISSUE TITLE
Dependecies

### ISSUE THREAD

**Issue by ljukas** [Litarvan/lightdm-webkit-theme-litarvan#19]
Hi!

I cannot get it to run. I just get errors:

** (lightdm-webkit2-greeter:11961): CRITICAL **: 10:50:45.372: void webkit_web_view_load_uri(WebKitWebView*, const gchar*): assertion 'WEBKIT_IS_WEB_VIEW(webView)' failed

runUnary$2@file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:7993:47
runUnaryGuarded$2@file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:7914:31
file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:8076:44
file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:2528:29
call$0@file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:4391:35
eval$1@file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:2159:31
_callInIsolate@file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:1805:34
file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:3267:34
file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:3288:24
file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:21897:27: CONSOLE LOG
file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:21889:24: CONSOLE LOG EXCEPTION: NullError: method not found: 'toLowerCase$0' on null
file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:21892:24: CONSOLE ERROR EXCEPTION: NullError: method not found: 'toLowerCase$0' on null
file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:21884:24: CONSOLE ERROR STACKTRACE:
file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:21884:24: CONSOLE ERROR toLowerCase$0$s@file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:25120:40
$get$1@file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:24641:34
$index@file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:24655:27
file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:23222:40
file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:21309:30
file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:5860:24
run$2@file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:7865:47
file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:21259:29
file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:21266:27

Are there any dependencies I need? Do I need dart to run it for example?

It looks really nice so would really like to get it to run.

I'm on a fresh Arch install with i3-gaps if that matters.

Regards

**Comment by ljukas** [comment]
I just used the AUR version. Which I guess means makepgd built it.

**Comment by Litarvan** [comment]
I tried a fix on 2.0.6 : https://aur.archlinux.org/packages/lightdm-webkit-theme-litarvan/

**Comment by ljukas** [comment]
Same for me.

**Comment by xorph** [comment]
Broken for me as well with the latest update.

**Comment by MrKickkiller** [comment]
Upon the latest update, the greeter also broke for me.
Currently removed it, but still having the issue where anytime I lock / open the device it reports an error happened in the current theme.

Lots of stack traces from the gnome-shell. I can provide those if wanted.

**Comment by Litarvan** [comment]
only the last update ? i hope it isn't a dart update bug 🤔 can you try using the old versions manual install ?

**Comment by MrKickkiller** [comment]
Mostly this caught my eye:

```
jun 04 20:43:32 Apollo systemd-coredump[11427]: Process 11416 (Xorg) of user 0 dumped core.
                                                
                                                Stack trace of thread 11416:
                                                #0  0x00007fdae77f086b raise (libc.so.6)
                                                #1  0x00007fdae77db40e abort (libc.so.6)
                                                #2  0x0000558b036ca60a OsAbort (Xorg)
                                                #3  0x0000558b036ca6ff FatalError (Xorg)
                                                #4  0x0000558b03800e1e n/a (Xorg)
                                                #5  0x00007fdae77f08f0 __restore_rt (libc.so.6)
                                                #6  0x00007fdae77f086b raise (libc.so.6)
                                                #7  0x00007fdae77db40e abort (libc.so.6)
                                                #8  0x00007fdae77db2e0 __assert_fail_base.cold.0 (libc.so.6)
                                                #9  0x00007fdae77e9112 __assert_fail (libc.so.6)
                                                #10 0x0000558b03798de9 dixRegisterPrivateKey (Xorg)
                                                #11 0x00007fdadcc5d2b9 glamor_init (libglamoregl.so)
                                                #12 0x00007fdadd2aa7ed n/a (modesetting_drv.so)
                                                #13 0x0000558b0378224d AddGPUScreen (Xorg)
                                                #14 0x0000558b037b7d9c n/a (Xorg)
                                                #15 0x0000558b036dcef6 n/a (Xorg)
                                                #16 0x0000558b0374d309 n/a (Xorg)
                                                #17 0x0000558b0374dab3 config_init (Xorg)
                                                #18 0x0000558b03809a27 InitInput (Xorg)
                                                #19 0x0000558b036ae644 n/a (Xorg)
                                                #20 0x00007fdae77dd06b __libc_start_main (libc.so.6)
                                                #21 0x0000558b036af21a _start (Xorg)
                                                
                                                Stack trace of thread 11421:
                                                #0  0x00007fdae582fffc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                #1  0x00007fdae0eb49c0 n/a (intel_drv.so)
                                                #2  0x00007fdae582a075 start_thread (libpthread.so.0)
                                                #3  0x00007fdae78b253f __clone (libc.so.6)
                                                
                                                Stack trace of thread 11424:
                                                #0  0x00007fdae582fffc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                #1  0x00007fdadc16dd84 n/a (nouveau_dri.so)
                                                #2  0x00007fdadc16da78 n/a (nouveau_dri.so)
                                                #3  0x00007fdae582a075 start_thread (libpthread.so.0)
                                                #4  0x00007fdae78b253f __clone (libc.so.6)
```
This would indicate an error in Xorg though, but I do remember updating this greeter recently. I'm somewhat knowledgeable with Linux, but Xorg is completely foreign territory for me.

----
```
jun 04 20:45:49 Apollo org.gnome.Shell.desktop[1042]: == Stack trace for context 0x562b8d19f040 ==
jun 04 20:45:49 Apollo org.gnome.Shell.desktop[1042]: #0 0x7ffd8745e260 b   resource:///org/gnome/shell/ui/tweener.js:80 (0x7f559c4c7cd0 @ 82)
jun 04 20:45:49 Apollo org.gnome.Shell.desktop[1042]: #1 0x7ffd8745e300 b   resource:///org/gnome/shell/ui/tweener.js:105 (0x7f559c4c7f78 @ 36)
jun 04 20:45:49 Apollo org.gnome.Shell.desktop[1042]: #2 0x7ffd8745e3a0 b   resource:///org/gnome/shell/ui/tweener.js:92 (0x7f559c4c7de0 @ 52)
jun 04 20:45:49 Apollo org.gnome.Shell.desktop[1042]: #3 0x7ffd8745f2c0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (0x7f559c4d2918 @ 54)
jun 04 20:45:49 Apollo org.gnome.Shell.desktop[1042]: #4 0x7ffd8745f410 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:337 (0x7f559c4d29a0 @ 1626)
jun 04 20:45:49 Apollo org.gnome.Shell.desktop[1042]: #5 0x7ffd8745f4c0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:350 (0x7f559c4d2a28 @ 100)
jun 04 20:45:49 Apollo org.gnome.Shell.desktop[1042]: #6 0x7ffd8745f550 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:365 (0x7f559c4d2ab0 @ 10)
jun 04 20:45:49 Apollo org.gnome.Shell.desktop[1042]: #7 0x7ffd8745f5d0 I   resource:///org/gnome/gjs/modules/signals.js:128 (0x7f559c4cff78 @ 386)
jun 04 20:45:49 Apollo org.gnome.Shell.desktop[1042]: #8 0x7ffd8745f680 b   resource:///org/gnome/shell/ui/tweener.js:207 (0x7f559c4cf5e8 @ 159)
jun 04 20:45:49 Apollo gnome-shell[1042]: Object Shell.GenericContainer (0x562b91050850), has been already finalized. Impossible to set any property to it.
jun 04 20:45:49 Apollo org.gnome.Shell.desktop[1042]: #9 0x7ffd8745f6f0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f559c4b5de0 @ 71)
jun 04 20:45:49 Apollo org.gnome.Shell.desktop[1042]: #10 0x7ffd8745f6f0 I   resource:///org/gnome/shell/ui/tweener.js:182 (0x7f559c4cf560 @ 15)
```

These types of stacktraces are also quite frequent in the logs, but I do remember them being there before this software.

**Comment by MrKickkiller** [comment]
Extra note: 
I'm not able to recall when the issues started exactly, but xorg-server (`1.20.0-2 -> 1.20.0-5`) got updated (on my machine) 2 days ago, and this greeter this morning (`2.0.5-1 -> 2.0.6-1`). However I do not recall having any issue yesterday. Could be wrong though. Looking back at my updates (of which there were quite a lot, holy hell), I also notice a VS code update deinstalled my nodejs 10 in favor of the LTS-carbon variant.

**Comment by Litarvan** [comment]
This doesn't look like an issue with my theme but an issue with lightdm itself, as its a native error and my theme is Javascript and the greeter is made in python. This also isn't the same error as the one of the thread. The greater update also, doesn't make any "breaking" change, you can look the code changes

**Comment by gvelchuru** [comment]
I manually rolled back to 2.0.4 and it's working completely fine with new lightdm, new xorg, etc

**Comment by MrKickkiller** [comment]
> This doesn't look like an issue with my theme but an issue with lightdm itself

Yea, while looking at the logs themselves in detail, I noticed it's a lot of C level code that is "breaking". Sorry :/

Just had "There are errors with this theme" thingy, and it immediately made me think the update to the them (2.0.6) was to "blame"

> I manually rolled back to 2.0.4

Tried doing the same, but no real progress (unless you faced the issue from OP)

**Comment by ZachariasZeiler** [comment]
For me 2.0.6 broke the theme too, 2.0.5 works. So I digged into the logs and stumbled about that: 

`file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:21889:24: CONSOLE LOG EXCEPTION: NoSuchMethodError: method not found: 'toLowerCase$0' (C.JSBool_methods.toLowerCase$0 is not a function. (In 'C.JSBo
ol_methods.toLowerCase$0(J.get$language$x(this._lightdm) === true || false)', 'C.JSBool_methods.toLowerCase$0' is undefined))`

I'm not familiar with javascript, but looks for me like one tries to invoke toUpperCase on a boolean. 
I guess here's the mistake as that's also the only change in the last commit: https://github.com/Litarvan/lightdm-webkit-theme-litarvan/blob/c9a128fb72c39f4e302e6b62243264b839dccad4/lib/translations.dart#L68

**Comment by ljukas** [comment]
Its weird that I get this error message even without the 2.0.6 version.

**Comment by gillhofer** [comment]
Can confirm, I get the same error with the same JavaScript function.

**Comment by dafta** [comment]
I can also confirm, downgrading to 2.0.4 fixes the issue.

**Comment by Litarvan** [comment]
I guess dart doesn't support this syntax, my bad on this ! Should have use an IDE, and the right syntax mostly... i pushed a fix, i'll release in a few minutes

**Comment by Litarvan** [comment]
Can someone try https://github.com/Litarvan/lightdm-webkit-theme-litarvan/releases/tag/v2.0.7 and tell me if it's ok before publishing to AUR ?

**Comment by el-dom** [comment]
Just tried it. 2.0.7 works.

**Comment by Litarvan** [comment]
Pushed on AUR ! https://aur.archlinux.org/packages/lightdm-webkit-theme-litarvan/
Thanks a lot all of you ! Didn't expect such an active community !

**Comment by ljukas** [comment]
If you make cool stuff you get an active community ;) I havn't tested if it solved my original issue yet, but will check first thing when I get home from work.

**Comment by MrKickkiller** [comment]
After getting the email that you pushed an update on AUR, I reinstalled the theme and magically it works again.

So either I was a complete derp and somehow messed up some file, or this was actually the issue that broke it for me.
Thx for the quick fix! Love this theme

**Comment by ljukas** [comment]
Tested at home, fixed for me aswell. So the original issue is gone. :) Thanks for fixing it!

**Comment by Litarvan** [comment]
@MrKickkiller In fact, the bug was that the `language` value provided by LightDM could be null, and i didn't handle that correctly, and by trying to fix this bug i did a big mistake so it broke it, i fixed both bugs and it now works !

@ljukas You are welcome :)
