### ISSUE TITLE
Color configuration

### ISSUE THREAD

**Issue by evamvid** [Litarvan/lightdm-webkit-theme-litarvan#23]
Is it possible to change the text and icon colors in some sort of configuration file? I think this would be a good feature in the case that the user's desired background image is lighter-colored, making it hard to read the white icons and text over a light background.

**Comment by Litarvan** [comment]
I agree this can be a real issue, i'll probably add this to 3.0 ( see #22 ).
Currently, here's what you can do to change the color text : 

Here's the line you must change :

https://github.com/Litarvan/lightdm-webkit-theme-litarvan/blob/54a922c26ac1661d3fc7ed3ecd4b6e8022d886e1/styles.css#L60

The file is situated in `/usr/share/lightdm-webkit/themes/litarvan/` on your filesystem.
You can change `white` to `black` or any hex color like `#ffeeee` for example (would look like this : `color: #ffeeee;`).

This will probably do the trick !

**Comment by Litarvan** [comment]
Fixed in 3.0, see src/_theme.scss file https://github.com/Litarvan/lightdm-webkit-theme-litarvan/blob/master/src/_theme.scss
