### ISSUE TITLE
Trying to change existing CSS

### ISSUE THREAD

**Issue by shahlin** [Litarvan/lightdm-webkit-theme-litarvan#24]
I'm trying to change the design a bit. Specifically, I'm trying to change the CSS of the displayed error and the login container. I can't seem to change it at all. I've tried changing the #error in `litarvan/packages/lightdm_webkit_theme_litarvan/components/login_component.css`. Still doesn't work.

Let me know if there's another way to do it

**Comment by Litarvan** [comment]
You need this shit installed too https://www.dartlang.org/

**Comment by shahlin** [comment]
Will 3.0 be available any soon?

**Comment by Litarvan** [comment]
I'm working on it, i planned to finish it late August/early September
