### ISSUE TITLE
option to disable splash screen and space button press

### ISSUE THREAD

**Issue by Zjemm** [Litarvan/lightdm-webkit-theme-litarvan#25]
Hi great theme. I found it today, and love it.

would it be possible to disable the arch splash screen?
and also would it be possible to disable the "press space" to login, but directly show the login field on boot?

if so, how would i change it to work that way?

**Comment by Litarvan** [comment]
Both are in 3.0 in the setup screen ! (Arch splash screen => "Disable intro", "Press space" => "Disable splash")

**Comment by adamtabrams** [comment]
Do you have a target date for when version 3.0 will be stable and released?

**Comment by Litarvan** [comment]
I'm just waiting for enough people to test things, and there are still things to add, but it should not be so long.

**Comment by Litarvan** [comment]
I just pushed a fix for a bug, you should try from `master`, if it doesn't work open a new issue with the lightdm logs

**Comment by Zjemm** [comment]
@wundrweapon did you test it already?

**Comment by Litarvan** [comment]
The fix i pushed wasn't about his bug, we are working on it on #27
