### ISSUE TITLE
Add Budgie-de Icon

### ISSUE THREAD

**Issue by vredesbyyrd** [Litarvan/lightdm-webkit-theme-litarvan#28]
Thanks for sharing your work. I have skipped display managers all together for years and opted to just 'startx'....but this theme caught my eye. And it works wonderfully. 

I will take a look at the source, but at some point if you could add an icon for Budgie DE that would great. 

Cheers.

**Comment by Litarvan** [comment]
Done ! I'll release new pre-release build tomorrow with it

**Comment by vredesbyyrd** [comment]
Awesome. Thanks much for the quick addition :)

**Comment by Litarvan** [comment]
Done : https://github.com/Litarvan/lightdm-webkit-theme-litarvan/releases/tag/v3.0.0-pre2
Sorry i'm a little late :)

**Comment by vredesbyyrd** [comment]
No sweat, thanks for your time and sharing your work!
