### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by wwwlad1slaw** [Litarvan/lightdm-webkit-theme-litarvan#3]
Hello! Is it possible to change the default background?

**Comment by Litarvan** [comment]
Sorry for not responsing, for people who will see this it is in `web/images/background.jpg`

**Comment by nsanal2** [comment]
Could you add this to the README?

**Comment by nsanal2** [comment]
Also the user icon instructions

**Comment by Litarvan** [comment]
Why not
