### ISSUE TITLE
Logo time change

### ISSUE THREAD

**Issue by JanczarKurek** [Litarvan/lightdm-webkit-theme-litarvan#30]
Hi, not an issue but rather a question - what is the simplest way to change duration of logo? I tried to put some short video, but i did not manage to find out a way to make it play longer than original logo. Can you help?

**Comment by Litarvan** [comment]
You mean, the OS logo ? Intro.vue, line 38, edit "2000" and replace it with something bigger (it's the duration in milliseconds).

https://github.com/Litarvan/lightdm-webkit-theme-litarvan/blob/master/src/views/Intro.vue#L38

**Comment by Gorzen** [comment]
Thanks, helped me to get exactly the feel I wanted !
