### ISSUE TITLE
scaled to big

### ISSUE THREAD

**Issue by Zjemm** [Litarvan/lightdm-webkit-theme-litarvan#31]
Hi i tried your new version v3.0.0-pre2.
now every thing is scaled way to big, like 4 time as big as normal.
the older version had the right scaling

but it sure looks good, keep up the good work :)

**Comment by Litarvan** [comment]
What is your screen resolution ?

**Comment by Zjemm** [comment]
3840 x 2160

**Comment by Litarvan** [comment]
It's very strange, people with this resolution complained on the old version because it was too small, so i made it bigger on >2000px screens. ( #18 )

Lightdm may have fixed it by themself, or my fix is working "too much", i'll try to figure it out

**Comment by Zjemm** [comment]
Hi,

i haven't had the time yet to test your workaround, it also not that big a problem, everything works (but bigger) :)

But it does seem to be that thats excactly the case, with these lines its scaled up again :)
now thats not an easy fix i think, because not all people are running latest versions like on arch linux.

so you might want to set it as an option in the settings screen?
just an idea

**Comment by Litarvan** [comment]
Good Idea, i'll try

**Comment by Litarvan** [comment]
Fixed in 3.0.0-pre3
