### ISSUE TITLE
[feature-request] Random background from directory

### ISSUE THREAD

**Issue by bbaserdem** [Litarvan/lightdm-webkit-theme-litarvan#32]
I was thinking a random background chosen from a directory would be a fun addition. Obviously a low priority, but could be nice if it can be done on the themeing end

**Comment by Litarvan** [comment]
I'm thinking (either before releasing 3.0 or for a 3.1 version) of a background customisation in the setup screen, i might add such a feature with it :) i'll let this issue open till

**Comment by Litarvan** [comment]
Done in the new release! (Option is in the Theming screen, accessible in the bottom-right corner on the Setup screen)
