### ISSUE TITLE
Dual monitor with different resolutions

### ISSUE THREAD

**Issue by xQsme** [Litarvan/lightdm-webkit-theme-litarvan#34]
I have a 1080p secondary monitor and a 1440p main monitor, the blur effect when entering the password is creating a black line at 1920px width, https://imgur.com/a/OQrE9lb

If you can let me know where in the src files the blur effect is located i can try to sort it out myself as you probably can't test this

Also while i'm at it, an option to disable the blur would be nice

**Comment by xQsme** [comment]
the background is the native resolution of my monitor, do you get monitor width/height anywhere in the code? it could be scanning my second monitor

**Comment by Litarvan** [comment]
I don't manage monitor width/height, it's html/css it's done normally, i also have dual screen and a 1920*1080 background and it works, i don't really understand, what does it looks without blur ? (on the clock screen)

**Comment by xQsme** [comment]
https://imgur.com/a/NOa2yAG

from what i've seen the blur itself shouldn't have this effect, not sure what could be causing it

**Comment by xQsme** [comment]
removed the blur class assignment and built the theme, the black bar is gone, the filter is causing it

**Comment by Litarvan** [comment]
It's extremely strange, looks like a bug in webkit itself.
New version of web greeter is using qt-webview, definetely better but currently definetely more stable.

I'll add an option to disable blur, until i do you should clone, delete the line and rebuild using (requires Node.JS) `npm i && npm run build`, then copy everything from the `dist/` folder to `/usr/share/lightdm-webkit/themes/litarvan/`

I'll let this issue open until i add the option, but i'll then close it as it's a webkit bug
