### ISSUE TITLE
24 hour 12 hour clock toggle

### ISSUE THREAD

**Issue by WingofaGriffin** [Litarvan/lightdm-webkit-theme-litarvan#35]
Just a nitpick. Allow users to choose if they want 24 hour or 12 hour clock in settings.

**Comment by WingofaGriffin** [comment]
Probably a smart idea

**Comment by LoneFenris** [comment]
Shouldn't this be controlled by the time_format configuration option in webkit2-greeter's config?

**Comment by WingofaGriffin** [comment]
It should be, but I tried playing around with it and nothing changed at all. The default value for it is LT auto, which should take the local defaults on that, with no dice. Even when I manually forced them to be US based with am pm, nothing changed. I think he has the time coded separately.

**Comment by LoneFenris** [comment]
Sorry, yes, I know that. My earlier comment was meant as a suggestion for how to implement localized time (12/24-hour). That is, as opposed to worrying about something like whether AM/PM should be included, just let moment.js handle figuring out the actual text.

I assume webkit2-greeter has some kind of API call to get the localized time using the settings in its config file, but maybe the theme has to call moment.js directly? Might be worth looking to see how the default antergos theme does it.

**Comment by Litarvan** [comment]
I'm not using webkit2 greeter API for this, i'm using it for langage and i'm using webkit locale function for date, but i implemented the clock manually. I'll have a look at it

**Comment by Litarvan** [comment]
Added in 3.0.0-pre3, you can enable it in the Setup screen

**Comment by WingofaGriffin** [comment]
12 Hour clock is still bugged. At midnight, is displays 0:XYam instead of 12:XYam

**Comment by Litarvan** [comment]
Oh that's my bad, i thought it was meant to be displayed this way so i implemented this myself, i'll reopen until i fix this

**Comment by Litarvan** [comment]
I updated the release, download it again and it should be good.

**Comment by ax00b3** [comment]
> you can enable it in the Setup screen
Can you be a bit more specific? How do I get to this setup screen?

**Comment by Litarvan** [comment]
The Setup screen is only on the pre-release which you can install manually from here https://github.com/Litarvan/lightdm-webkit-theme-litarvan/releases
