### ISSUE TITLE
Options Button not visible

### ISSUE THREAD

**Issue by sambadevi** [Litarvan/lightdm-webkit-theme-litarvan#36]
The options button from the live preview isn't visible after installing

I installed the theme with `pacman -S pacman -S lightdm-webkit-theme-litarvan`

I'm using lightdm-webkit2-greeter and the theme is displaying correctly, however I can't edit the configuration to enable round-avatar pictures for example. And I didn't find any info regarding the option button in the readme.

**Comment by Litarvan** [comment]
Official repositories still have 2.* version, while the settings button was added in 3.0 (which is, if you look closer, way different), which is still in pre-release.

Still you can download and install it manually on the release page : https://github.com/Litarvan/lightdm-webkit-theme-litarvan/releases/download/v3.0.0-pre2/lightdm-webkit-theme-litarvan-3.0.0-pre2.tar.gz

**Comment by FFY00** [comment]
@Litarvan are the pre-releases stable? I can update the package.

**Comment by Litarvan** [comment]
I'll try to publish a stable version but first i need to close a couple of issue (by the way, thanks for maintaining this package on the official repos :) )

**Comment by FFY00** [comment]
No problem :) Just @ on new releases so that I don't miss them.
