### ISSUE TITLE
Error loading theme

### ISSUE THREAD

**Issue by Shiftiing** [Litarvan/lightdm-webkit-theme-litarvan#37]
Hello,

I really appreciate this theme but I can't load the theme when I launch lightdm. I have to load the default theme if not I have a black screen

Someone could help me ?

Thanks

**Comment by Litarvan** [comment]
Can you tell me how did you install the theme ? And which version ?

**Comment by WtGuy** [comment]
I am also experiencing this issue on an installation of Arch (Arch Labs to be specific).

LightDM Version: 1.28
Litervan Version: 2.0.7-3 (The one found in the community packages)

It was installed using pacman.

Please let me know if there is any other information you need.

**Comment by Litarvan** [comment]
Can you both give me your /var/log/lightdm/seat0.log ? (You need root permission to print this)

**Comment by Shiftiing** [comment]
Here is my /var/log/lightdm/seat0-greeter.log :

** (lightdm-webkit2-greeter:7136): WARNING **: 00:52:23.060: [ERROR] :: A problem was detected with the current theme. Falling back to default theme..

**Comment by Shiftiing** [comment]
Ok, I resolved my issue by rebuilding the tar file and extract it again.
Thanks

**Comment by zany130** [comment]
I have this same issue says there was a problem with the theme and that it needed to load the default. Im on manjaro and I installed through the aur
