### ISSUE TITLE
blackscreen.

### ISSUE THREAD

**Issue by LPW00** [Litarvan/lightdm-webkit-theme-litarvan#38]
in the settings there is a icon on the bottom right corner, pressing on it reveals a blackscreen. and in the main settings screen, the text is invisible and so i had to try to remember the options from the web preview. i use the latest release from github on arch. Also i struggle to enable manual user name input...

**Comment by Litarvan** [comment]
It's not an issue, it's currently work in progress haha
About the manual user name input, i don't really understand, the username field is automatically focused when entering the login page
