### ISSUE TITLE
Current pre-release version not grabbing avatar

### ISSUE THREAD

**Issue by bundito** [Litarvan/lightdm-webkit-theme-litarvan#41]
I've got my avatar set (from within Plasma, on Manjaro), but the greeter only shows me the generic user avatar. If I run `lightdm --test-mode` in Plasma, it pulls my avatar (although the window is so small the layout is all messed up). 

Any idea what's going on? Can I help?

**Comment by Litarvan** [comment]
I'm getting the avatar from the Webkit Greeter API, you should open an issue on it for such things.
For me, the solution was to set an avatar in my desktop settings (Plasma)

**Comment by bundito** [comment]
I set mine in Plasma also. It works in the Plasma internals, works in test mode, but not in the theme. Interesting. I’ll keep trying to figure this out. Thanks for the answer.
