### ISSUE TITLE
Cannot start version 3.0.0 pre 3

### ISSUE THREAD

**Issue by Antonio210696** [Litarvan/lightdm-webkit-theme-litarvan#45]
I've tried to manually install the pre 3 of 3.0.0 but it seems that there is a problem with IBus (at least it is the first error that ti returns). When launching lightdm-webkit2-greeter from cli, the greeter window appears black and eventually returns an error asking to load fallback theme. Meanwhile, in console, i get the following

> (lightdm-webkit2-greeter:2515): IBUS-WARNING **: 10:18:24.634: Unable to connect to 
> ibus: Impossibile connettersi: Connessione rifiutata
> CONSOLE WARN The resource file:///usr/share/lightdm-webkit/themes/litarvan/app.225ea7ba.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
> CONSOLE WARN The resource file:///usr/share/lightdm-webkit/themes/litarvan/app.46f3f1a8.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.

I have simply untared the archive in /usr/share/lightdm-webkit/themes/litarvan

**Comment by Litarvan** [comment]
Can I have the complete console content ?

**Comment by Antonio210696** [comment]
This is the whole console content, the line before was just the prompt of my terminal. I have now tried again to make it work, but it seems that that the two `CONSOLE WARN` messages have been suppressed; still the theme doesn't work and asks me to fallback to default theme. I guess the problem is not there. I have tried to activate debug mode, but I don't know where to get any log. If you tell me where to find it I can attach...

Any way, the output of the console now is (the whole output):

>  lightdm-webkit2-greeter 

> 
> (lightdm-webkit2-greeter:1417): IBUS-WARNING **: 10:07:19.856: Unable to connect to ibus: Impossibile connettersi: Connessione rifiutata
> 
> ** (lightdm-webkit2-greeter:1417): WARNING **: 10:07:33.945: [ERROR] :: A problem was detected with the current theme. Falling back to default theme...
> file:///usr/share/lightdm-webkit/themes/simple/index.html:194:10: CONSOLE ERROR ReferenceError: Can't find variable: lightdm
>

**Comment by Litarvan** [comment]
Very strange, it looks like a bug with lightdm-webkit itself, the theme may also be not loaded ?
What do you have in `/etc/lightdm/lightdm-webkit2-greeter.conf` ?

**Comment by Antonio210696** [comment]
here it is:

> #
```
# [greeter]
# debug_mode          = Greeter theme debug mode.
# detect_theme_errors = Provide an option to load a fallback theme when theme errors are detected.
# screensaver_timeout = Blank the screen after this many seconds of inactivity.
# secure_mode         = Don't allow themes to make remote http requests.
# time_format         = A moment.js format string so the greeter can generate localized time for display.
# time_language       = Language to use when displaying the time or "auto" to use the system's language.
# webkit_theme        = Webkit theme to use.
#
# NOTE: See moment.js documentation for format string options: http://momentjs.com/docs/#/displaying/format/
#

[greeter]
debug_mode          = false
detect_theme_errors = false
screensaver_timeout = 300
secure_mode         = true
time_format         = LT
time_language       = auto
webkit_theme        = litarvan

#
# [branding]
# background_images = Path to directory that contains background images for use by themes.
# logo              = Path to logo image for use by greeter themes.
# user_image        = Default user image/avatar. This is used by themes for users that have no .face image.
#
# NOTE: Paths must be accessible to the lightdm system user account (so they cannot be anywhere in /home)
#

[branding]
background_images = /usr/share/backgrounds
logo              = /usr/share/pixmaps/archlinux-logo.svg
user_image        = /usr/share/pixmaps/archlinux-user.svg
```

I am currently using stable version 2.0.7, but from docs I guess I should keep the same conf for all versions, right? I have already faced once a similar issue; back then it was a permission problem. Could it be the same?

**Comment by Antonio210696** [comment]
I actually had to change permissions (didn't have the x for the directory). Now i get this

> $ lightdm-webkit2-greeter 
> file:///usr/share/lightdm-webkit/themes/litarvan/chunk-vendors.ebe8158a.js:7:11122: CONSOLE ERROR TypeError: undefined is not an object (evaluating 'N[T().substring(0,2)][t]')
> CONSOLE WARN The resource file:///usr/share/lightdm-webkit/themes/litarvan/app.9dabefea.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
> CONSOLE WARN The resource file:///usr/share/lightdm-webkit/themes/litarvan/app.f9b72de3.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
> CONSOLE WARN The resource file:///usr/share/lightdm-webkit/themes/litarvan/chunk-vendors.ebe8158a.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
> 

Hope that it can help

**Comment by Litarvan** [comment]
What version of lightdm-webkit2-greeter do you have ?

**Comment by Antonio210696** [comment]
Last version (2.2.5-2)

**Comment by JpegXguy** [comment]
I get the exact same error. (That latest one) Seems to be the theme's fault.

**Comment by Litarvan** [comment]
I've got this error multiple times and everytime it was actually from a value given by the greeter API, normally the only "nullable" value is the langage which i'm checking, i'll try to see what other values can be nullables, but it sucks that some values are randomly undefined on 0.1% computers.

**Comment by Core00077** [comment]
got the exact same error here too. using both lightdm and test mode, no luck.
tried with the released version on github and the built version(by myself). 

versions are:
- lightdm-webkit2-greeter: 2.2.5-2
- litarvan: pre-3.0.0

```bash
$ lightdm-webkit2-greeter --test-mode
Gtk-Message: 16:43:55.515: Failed to load module "appmenu-gtk-module"
Gtk-Message: 16:43:55.648: Failed to load module "appmenu-gtk-module"
file:///usr/share/lightdm-webkit/themes/litarvan/js/chunk-vendors.b4a3ade3.js:7:12024: CONSOLE ERROR TypeError: undefined is not an object (evaluating 'B[M().substring(0,2)][t]')
CONSOLE WARN The resource file:///usr/share/lightdm-webkit/themes/litarvan/css/app.73b63c63.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
CONSOLE WARN The resource file:///usr/share/lightdm-webkit/themes/litarvan/js/app.13efb685.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
CONSOLE WARN The resource file:///usr/share/lightdm-webkit/themes/litarvan/js/chunk-vendors.b4a3ade3.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
```

still wondering why it happens randomly. here's information about my laptop.

```yaml
 core@core-pad
 OS: Manjaro 18.1.0 Juhraya
 Kernel: x86_64 Linux 4.19.69-1-MANJARO
 Uptime: 40m
 Packages: 1526
 Shell: zsh 5.7.1
 Resolution: 3840x1080
 DE: KDE 5.61.0 / Plasma 5.16.4
 WM: KWin
 GTK Theme: Breath [GTK2/3]
 Icon Theme: Adwaita
 Font: Noto Sans Regular
 Disk: 590G / 1.8T (35%)
 CPU: Intel Core i5-7200U @ 4x 3.1GHz [61.0°C]
 GPU: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
 RAM: 2429MiB / 15906MiB
```

**Comment by Litarvan** [comment]
Fixed on release, it happened when an unknown langage was used

**Comment by frahman944** [comment]
hey! issue's still up

`❯ doas cat seat0-greeter.log    
CONSOLE OTHER WARN The resource file:///usr/share/lightdm-webkit/themes/litarvan/css/app.6fe6ebad.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
❯ uname -a
Linux gulp 5.18.15-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 29 Jul 2022 22:52:39 +0000 x86_64 GNU/Linux`


`community/lightdm-webkit2-greeter 2.2.5-6 [installed]
    LightDM greeter that uses WebKit2 for theming via HTML/JavaScript.
    extra/lightdm 1:1.30.0-4 [installed]
    A lightweight display manager`
