### ISSUE TITLE
[Question] Release plan

### ISSUE THREAD

**Issue by lukasbash** [Litarvan/lightdm-webkit-theme-litarvan#52]
Hi there,

first of all I want to say that this is my favorite theme out there. It is elegant and simple.
The customization of the 3.0 release makes it perfect.

I just wanted to know what your release plans are and if there are any problems that are currently blocking a 3.0 release? I am using Arch Linux and can't wait to see a 3.0 on my machine.

**Comment by Litarvan** [comment]
Hi ! Thanks a lot for your compliment first,
I wanted to add some more customizations to the theme, and close issues related to the pre-release before releasing it.

Thing is, the fact that lightdm-webkit2-greeter uses a very old version of webkit, makes both of these things kinda hard.

And recently, Antergos has been discontinued, and lightdm-webkit2-greeter too as it was a part of it. I'm looking for forking it / creating a new one, but for now i should maybe create a lightdm-webkit-theme-litarvan-git on AUR.

**Comment by lukasbash** [comment]
> I'm looking for forking it / creating a new one
A new greeter? Or a new theme?

> for now i should maybe create a lightdm-webkit-theme-litarvan-git on AUR.
That would be seriously amazing.

**Comment by JpegXguy** [comment]
Exactly, create a git PKGBUILD

**Comment by Litarvan** [comment]
I've decided to finally release the 3.0 as fast as i can, i've nearly finished the last feature i wanted (theming screen), i just need to finish my little "hacks" to customize svg and other things

**Comment by Litarvan** [comment]
Finally released it for real, sorry for the very long delay (a bit of explanations here : #68 )
