### ISSUE TITLE
Arch/Gnome - Switch User option does nothing

### ISSUE THREAD

**Issue by Strykar** [Litarvan/lightdm-webkit-theme-litarvan#56]
I'm on `Arch Linux/Gnome 3.32.2` the `Switch User` option, just above `Logout` does not work, I'm uncertain if this is greeter related but it worked with [lightdm-webkit2-greeter](https://www.archlinux.org/packages/community/x86_64/lightdm-webkit2-greeter/)

**Comment by Litarvan** [comment]
:thinking: Are you on the right page ? I'm not sure there is a "Switch User" option under "Logout", can you make a screenshot of this ?

**Comment by Strykar** [comment]
I mean the Gnome DE Switch user option
![Screenshot from 2019-08-09 16-50-31](https://user-images.githubusercontent.com/2946372/62775792-50005200-bac6-11e9-93d3-f930056fddb8.png)

**Comment by Litarvan** [comment]
After some research, it looks like the Switch User option does not work until you use GDM
I'm closing this since it's a GNOME issue
