### ISSUE TITLE
Setup is run on every boot

### ISSUE THREAD

**Issue by arbaes** [Litarvan/lightdm-webkit-theme-litarvan#57]
Is there any way to prevent this and keeping the setup result ?

**Comment by Litarvan** [comment]
I simply use localStorage to save settings, if you get the setup screen on every boot it means there is an issue with how lightdm-webkit2-greeter implements it, sorry but as it is not maintained anymore there is no real solution :/

**Comment by arbaes** [comment]
I see, seems I'll stay with SDDM for now. Thank you for your reply.

**Comment by WesGtoX** [comment]
I'm using the theme, which by the way, very beautiful congratulations @Litarvan! But here I have no problem with the setup, is running normal, with the settings set.

**Comment by Litarvan** [comment]
This issue may happen if you used keyboard instead of clicking on the back button to close the setup screen, if it's was this, then it is fixed in the release.

**Comment by arbaes** [comment]
I'll check, thank you for keeping me updated !
