### ISSUE TITLE
Installation guide doesnt seem to be enough?

### ISSUE THREAD

**Issue by thepenguinthatwants** [Litarvan/lightdm-webkit-theme-litarvan#60]
Hi!

I've being trying to set this theme but nothing seems to work.

`pacman -S lightdm-webkit-theme-litarvan`

`sudo vim /etc/lightdm/lightdm.conf`
under the section
[LightDM]
greeter-session=lightdm-webkit2-greeter

`sudo vim /etc/lightdm/lightdm-webkit.conf`
#seems like there was no such file earlier so I wrote
theme = litarvan

OOh it was a wrong file.. my typo sorry!

**Comment by thepenguinthatwants** [comment]
Checking the logs 

`sudo less /var/log/lightdm/seat0-greeter.log`

(lightdm-gtk-greeter:695): Gtk-WARNING **: 17:19:48.480: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node menubar owner GreeterMenuBar)

**Comment by thepenguinthatwants** [comment]
Oh it was needed to be under the seat section. It works .. sorry for this issue

**Comment by Litarvan** [comment]
It says "lightdm-gtk-greeter" which means you did something wrong on editing lightdm.conf, you are supposed to edit greeter-session for the [Seat:*] section, not an issue with the theme
