### ISSUE TITLE
main.dart.js ?

### ISSUE THREAD

**Issue by cmacht** [Litarvan/lightdm-webkit-theme-litarvan#67]
Hi, I can't get the theme to run. I see the first logo but get: "An error was detected in the current theme that could interfere with the system login process.".

These lines from `/var/log/lightdm/seat0-greeter.log` seem like a hint, but I can't figure out what to do next:

    file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:21897:27: CONSOLE LOG
    file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:21889:24: CONSOLE LOG EXCEPTION: Error in asset:lightdm_webkit_theme_litarvan/lib/components/app/app_component.html:1:0
    file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:21892:24: CONSOLE ERROR EXCEPTION: Error in asset:lightdm_webkit_theme_litarvan/lib/components/app/app_component.html:1:0
    file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:21884:24: CONSOLE ERROR ORIGINAL EXCEPTION: RangeError (index): Index out of range: no indices are valid: 0
    file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:21884:24: CONSOLE ERROR ORIGINAL STACKTRACE:
    file:///usr/share/lightdm-webkit/themes/litarvan/main.dart.js:21884:24: CONSOLE ERROR wrapException@file:///urs/share/lightdm-webkit/themes/litarvan/main.dart.js:3119:26

**Comment by Litarvan** [comment]
It looks like you are using the 2.x version, this is probably fixed on the 3.x one (you can download it from the releases page : https://github.com/Litarvan/lightdm-webkit-theme-litarvan/releases )
