### ISSUE TITLE
Not optimal on 4k/big screens

### ISSUE THREAD

**Issue by FFY00** [Litarvan/lightdm-webkit-theme-litarvan#73]
Hey, somewhat like a 1 month ago I got myself a new 32' 4K screen. This worked fine in the previous version but it's a bit problematic in the new one. The main issue is that the background does not zoom in to fit the screen, instead it repeats itself. The blur is also too big, I can notice squares, it's not smooth.

**Comment by Litarvan** [comment]
That's pretty strange, I remember it working good on my 4K monitor, do you have a photo or a screenshot ? Does it look the same in the LightDM debug mode (`lightdm-webkit2-greeter` command in a terminal) and in the browser ?

**Comment by FFY00** [comment]
Ah, sorry I forgot the exact symptoms when I reported it. Basically when the blur starts it add some black lines.

**Comment by FFY00** [comment]
https://photos.app.goo.gl/FKdGCmV51cRzNVTBA

**Comment by Litarvan** [comment]
???? This is so strange! I do not have my 4K monitor currently but I'll try something to reproduce

**Comment by kylelaker** [comment]
I am able to see the same behavior. It almost looks like the same effect that is being applied to the borders/edges of the screen. It starts out as a very fine, thin black line and then thickens and blurs (as the rest of the background blurs).

**Comment by Demalpheus** [comment]
I'm seeing a similar issue on my screen, 3440x1440 resolution. also some of the options in the settings section are not accessible as they are drawn off scren.

**Comment by Litarvan** [comment]
I think i get it, lightdm-webkit-greeter does not manage the screen dpi, so on high dpi i had to use "zoom: 2.0", which is probably buggy because yay webkit-gtk, and is also too much if you have a a hi dpi resolution less than 4k

I'll have to wait until next week to have my 4k monitor available, and then i'll try to debug as much as possible

**Comment by FFY00** [comment]
[xvfb](https://en.wikipedia.org/wiki/Xvfb) allows you to create a virtual xorg server, you can use that to emulate an HiDpi display.

**Comment by Kage-Yami** [comment]
I'm experiencing the same issue here; not sure what else is helpful, but here's a screenshot of the issue reproduced by launching `lightdm-webkit2-greeter` from a terminal and configuring the same as my actual setup:

![image](https://user-images.githubusercontent.com/2202488/71553713-a6fbc900-2a5f-11ea-9db2-82dbf24a3371.png)

That test was done at 2560x1440 (Budgie Desktop - Arch Linux). Setting the resolution to 3840x2160 results in similar issues, albeit with the black line closer to the center, and a new horizontal line near the bottom. Issue is not present at 1920x1080.

**Comment by AkitakiKou** [comment]
I got similar result as other comments at 2560x1600 (Manjaro Linux). The black line occurs only on the blurred login page and not other pages.

![image](https://user-images.githubusercontent.com/17219127/71777937-22222980-2fe2-11ea-94ef-1ec8ed8205c2.png)
![image](https://user-images.githubusercontent.com/17219127/71777940-264e4700-2fe2-11ea-865c-3889f9b7ad14.png)

**Comment by CocaineJohnsson** [comment]
I can verify the same issue running in 4K, screenshot taken with lightdm-webkit2-greeter debug mode (does not present in firefox)

Noticeable pixelation, image scaling incorrectly (the black bars... I'd assume they are the edge-fade effect), irrespecctive of the 'disable 2x scaling (large screen fix)' setting.

For the time being I'll just use a black background -- feels the most elegant solution

![demonstration](https://i.imgur.com/uakSzvS.png)

**Comment by Litarvan** [comment]
Looks like it was indeed a bug from Webkit. After struggling with my broken computer and xvfb (thanks a lot for the tip btw) I found that setting the background div position: absolute; instead of fixed, fixes the thing (for some reason).

Can someone build from master to test if it's working for him too ?

**Comment by CocaineJohnsson** [comment]
Yeah, that seems to have fixed it.
And it fixed my busted awesomeWM icon, it's now rendering correctly again.

npm audit says there are 5 vulns, 4 of which are serious -- apparently. I'm not familiar enough with web tech to know how much stock to put into that build message but I figured I'd mention it anyway.

Screenshot:
![fixed screenshot](https://i.imgur.com/k8qeI15.png)

**Comment by Litarvan** [comment]
Nice ! I'll update dependencies before releasing don't worry
