### ISSUE TITLE
Where is the config stored?

### ISSUE THREAD

**Issue by phunni** [Litarvan/lightdm-webkit-theme-litarvan#74]
I'm trying to install and use Litarvan on an immutable and stateless system - so the setup is running every time because the config can't be persisted!
If I could just figure out where the config is being stored, I could copy it into the build scripts that create the system image...

**Comment by Litarvan** [comment]
It's stored in the local storage, so probably in the Webkit data directory.
According to this : https://github.com/Antergos/web-greeter/blob/stable/meson_options.txt
it may be somewhere in /usr/lib/lightdm-webkit2-greeter I guess ? It may not be a text file

**Comment by Litarvan** [comment]
Closed for inactivity, feel free to reopen if you still need help
