### ISSUE TITLE
[Feature Request] Hibernate button

### ISSUE THREAD

**Issue by Acatorn** [Litarvan/lightdm-webkit-theme-litarvan#75]
Thank you for your great work, man. One thing that is missing for me is a hibernate button. There are Poweroff, Reboot, Suspend and only Hibernate is missing;)
Is there a chance to implement this?

**Comment by Litarvan** [comment]
Good idea, i'll implement this for the next version

**Comment by Litarvan** [comment]
Done in 3.1.0
