### ISSUE TITLE
Doesn't recongize keypress

### ISSUE THREAD

**Issue by logantalley** [Litarvan/lightdm-webkit-theme-litarvan#79]
I got it working the first time, and it was glorious, but now I can't access anything. It says 'Press enter or space to login' and then it won't respond to any key. Nothing. I tried enabling debug mode but still I couldn't get it to work.

**Comment by Litarvan** [comment]
Do you have multiple monitors ?

**Comment by logantalley** [comment]
I do. However I tried it with external monitors disconnected and still no luck

**Comment by daubneyi** [comment]
I believe that I have a very similar issue.

**Comment by Litarvan** [comment]
When I had multiple monitors, I had to click with my mouse on the one with LightDM to make the keyboard usable.
But if it's related to time, logs would in fact be useful. They should be in /var/log/lightdm/seat0-greeter.log (superuser is needed to read those). It should be quite short.
