### ISSUE TITLE
Suspend

### ISSUE THREAD

**Issue by dimmuboy** [Litarvan/lightdm-webkit-theme-litarvan#8]
Can you add suspend option please?

**Comment by Litarvan** [comment]
I'll work on it for the v3 !

**Comment by dimmuboy** [comment]
Thanks, when is planned?

**Comment by Litarvan** [comment]
I will start this afternoon, i'm not planning to change a lot of things but the most important changes will be customization (like the wallpaper), code cleaning, and slow-computer support (option to disable animations)

**Comment by dimmuboy** [comment]
Thanks, great to read
Goog luck  :)

**Comment by Litarvan** [comment]
Fixed in 3.0
