### ISSUE TITLE
Terrible performance on v3.1.0

### ISSUE THREAD

**Issue by soanvig** [Litarvan/lightdm-webkit-theme-litarvan#81]
Hi! I just updated to v3.1.0, and on my 4k screen I have terrible performance problems - any input or click takes seconds to perform.

Also, the bug with "box shadow cross" is still the issue, but only on the first screen (the second one, with password is OK).

Litarvan: 3.1.0
LightDM: 1.30.0
LighDM Webkit Greeter: 2.2.5-2

**Comment by soanvig** [comment]
The performance is OK if I launch webkit greeter manually after logging in (and it somehow starts another session, but anyway, the problem is gone then).

**Comment by Litarvan** [comment]
What version were you using previously ? Was the HiDPI integration OK ?

**Comment by soanvig** [comment]
I believe it was 3.0.0, and HiDPI was OK, but I had the "box shadow" issue.

**Comment by DonRichie** [comment]
@soanvig: Can you please share more information how you fixed this issue?
I have exactly the same behaviour on my 4k display.

**Comment by bwhissel** [comment]
HiDPI here too. Love the theme, but it takes several seconds after a keypress before the response is presented. I'm not sure how to begin debugging, but happy to help.

**Comment by Litarvan** [comment]
Unfortunately the theme uses an old version of webkit which is very buggy. I added a 'blur settings' view on the 3.2.0 (accessible from the setup page) where you can select differents blur methods. You can select the one that works the best for you, and the lags should go away.
