### ISSUE TITLE
Disable fade to black

### ISSUE THREAD

**Issue by 132ikl** [Litarvan/lightdm-webkit-theme-litarvan#9]
Is there anyway to disable the fade to black between press log in and the desktop? I have the same background set for the greeter and for my desktop, so I would like to have a seamless fade. I'd be fine with editing the files just for myself, but I don't know a whole ton about dart.

**Comment by Litarvan** [comment]
I'll define an option to disable it if you want, but i don't think it's really possible for your desktop and lightdm to not have at least 1s of black screen when launching your desktop, this is also why i at first put that fade !

**Comment by 132ikl** [comment]
I believe that because it's just an X server, if you set a wallpaper
beforehand with a tool like feh it will continue to display while loading
your desktop environment (although this may be different if you use a full
desktop environment, I personally use i3)

**Comment by Litarvan** [comment]
Fixed in 3.0 (option to disable fade in setup screen)

**Comment by Litarvan** [comment]
Just tested myself, works good but i may consider fading just the login form and the blur while keeping the background, as currently when desktop launches blur and login form just dissapear.

**Comment by 132ikl** [comment]
thanks :)
