### ISSUE TITLE
Wrong Time on greeter

### ISSUE THREAD

**Issue by vibhav1011** [Litarvan/lightdm-webkit-theme-litarvan#90]
The time displayed on the greeter is not the same as the system time and I couldn't find an option to set time in the .config file for webkit-2 or the GUI on the greeter.
Not sure is this is an issue just for me, but any help would be appreciated.

**Comment by Litarvan** [comment]
I need more information, what is the difference between the right and the wrong time?

**Comment by vibhav1011** [comment]
the system time and the time displayed on the greeter are not same. I tried to set it manually but that didn't work either. On Apr 20, 2021 16:38, Adrien Navratil ***@***.***> wrote:
I need more information, what is the difference between the right and the wrong time?

**Comment by Litarvan** [comment]
What distro are you using, and what is the output of `sudo timedatectl`?

**Comment by vibhav1011** [comment]
I'm using Manjaro xfce.

Output of timedatectl :

Local time: Tue 2021-04-20 16:53:52 IST
           Universal time: Tue 2021-04-20 11:23:52 UTC
                 RTC time: Tue 2021-04-20 11:23:53
                Time zone: Asia/Kolkata (IST, +0530)
System clock synchronized: no
              NTP service: inactive
          RTC in local TZ: no

________________________________

**Comment by Litarvan** [comment]
Your ntp service is inactive and your system clock not synchronized, I think that's the reason :) try doing those commands : 
```
$ sudo timedatectl set-ntp true
$ sudo hwclock --systohc
```
the output of `sudo timedatectl` should then print `System clock synchronized: yes` and `NTP service: active`, tell if the theme has the right time after that (you may have to restart lightdm or even your computer).

**Comment by Litarvan** [comment]
Actually the 'System clock synchronized: no' appear to be normal, but the NTP service should be active

**Comment by vibhav1011** [comment]
Thanks!

________________________________
