### ISSUE TITLE
Installing archlinux-wallpaper causes issues

### ISSUE THREAD

**Issue by GhostSquad57** [Litarvan/lightdm-webkit-theme-litarvan#92]
So for some odd reason, after installing `archlinux-wallpaper`, the login manager displays an error and I have to load to a default theme to continue to login.
If I reboot the machine I'm thrown into a black screen, unable to login.
Uninstalling `archlinux-wallpaper` fixes this issue.

**Comment by GhostSquad57** [comment]
![IMG_20200429_014851](https://user-images.githubusercontent.com/1379876/80564615-46a07800-89bc-11ea-8469-9f87e80c9f43.jpg)
Here's a picture of the error

**Comment by Litarvan** [comment]
3.2.0 should fix this, installing archlinux-wallpaper didn't cause any error on my test machine
