### ISSUE TITLE
Lock screen

### ISSUE THREAD

**Issue by MangaD** [Litarvan/lightdm-webkit-theme-litarvan#93]
Hello, this is unlikely to be a problem with the theme, but perhaps someone can help me with this issue. I have changed the LightDM theme as instructed, using webkit2 and litarvan. It works very well, except that when I lock screen (using xscreensaver), it uses the gtk theme... Is there any way to solve this?

**Comment by Litarvan** [comment]
I've seen people configuring their environment and lightdm for this to work, but I can't really do anything on my own as far as I know, sorry :/
