### ISSUE TITLE
Background chooser crash

### ISSUE THREAD

**Issue by MangaD** [Litarvan/lightdm-webkit-theme-litarvan#94]
Hello, I was having a problem with the theme crashing (the famous "An error detected in the current theme that could interfere with the system login process" problem) when I got to the theme settings with the background chooser. I found out that the following configuration needs to be set, and I suggest putting it up in the readme. ;)

In file `/etc/lightdm/lightdm-webkit2-greeter.conf`, under `[branding]`, make sure you have:
```
background_images = /usr/share/backgrounds
```

**Comment by Litarvan** [comment]
Fixed in 3.2.0, thanks for your detailed report :)
