### ISSUE TITLE
Error on building

### ISSUE THREAD

**Issue by los95** [Litarvan/lightdm-webkit-theme-litarvan#96]
Hello, I don't know if this is appropriate to ask but I am having problems with building litarvan.
I get this error after attempt:

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lightdm-webkit-theme-litarvan@3.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lightdm-webkit-theme-litarvan@3.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Litarvan** [comment]
I think this is simply due to the fact you were building a work in progress commit, or a missing `node_modules`. It should work on master right now.
