### ISSUE TITLE
Xubuntu session icon

### ISSUE THREAD

**Issue by rauldipeas** [Litarvan/lightdm-webkit-theme-litarvan#98]
Could you include icon for Xubuntu session? It's showing Ubuntu logo.

**Comment by Gorzen** [comment]
What do you mean? Do you mean XFCE? Xubuntu is not a window manager nor a desktop environment I don't see how it can pop up in lightdm. But XFCE should already display correctly so I don't understand your issue

**Comment by Gorzen** [comment]
Do you mean XFCE? XCFE is already present.

**Comment by rauldipeas** [comment]
Xubuntu has it's own session icon, other than XFCE.

**Comment by Litarvan** [comment]
The check was looking for 'ubuntu', which matched 'xubuntu', explaining your issue. This should have been fixed in the 3.2.0.
